# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: protobuf/eigr/actor.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import any_pb2 as google_dot_protobuf_dot_any__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x19protobuf/eigr/actor.proto\x12\x0b\x65igr.actors\x1a\x19google/protobuf/any.proto\"\x80\x01\n\x08Registry\x12\x31\n\x06\x61\x63tors\x18\x01 \x03(\x0b\x32!.eigr.actors.Registry.ActorsEntry\x1a\x41\n\x0b\x41\x63torsEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12!\n\x05value\x18\x02 \x01(\x0b\x32\x12.eigr.actors.Actor:\x02\x38\x01\"D\n\x0b\x41\x63torSystem\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\'\n\x08registry\x18\x02 \x01(\x0b\x32\x15.eigr.actors.Registry\"T\n\x15\x41\x63torSnapshotStrategy\x12/\n\x07timeout\x18\x01 \x01(\x0b\x32\x1c.eigr.actors.TimeoutStrategyH\x00\x42\n\n\x08strategy\"V\n\x17\x41\x63torDeactivateStrategy\x12/\n\x07timeout\x18\x01 \x01(\x0b\x32\x1c.eigr.actors.TimeoutStrategyH\x00\x42\n\n\x08strategy\"\"\n\x0fTimeoutStrategy\x12\x0f\n\x07timeout\x18\x01 \x01(\x03\"\x8f\x01\n\nActorState\x12/\n\x04tags\x18\x01 \x03(\x0b\x32!.eigr.actors.ActorState.TagsEntry\x12#\n\x05state\x18\x02 \x01(\x0b\x32\x14.google.protobuf.Any\x1a+\n\tTagsEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\t:\x02\x38\x01\"\xd3\x01\n\x05\x41\x63tor\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\x12\n\npersistent\x18\x02 \x01(\x08\x12&\n\x05state\x18\x03 \x01(\x0b\x32\x17.eigr.actors.ActorState\x12=\n\x11snapshot_strategy\x18\x04 \x01(\x0b\x32\".eigr.actors.ActorSnapshotStrategy\x12\x41\n\x13\x64\x65\x61\x63tivate_strategy\x18\x05 \x01(\x0b\x32$.eigr.actors.ActorDeactivateStrategyBR\n!io.eigr.functions.protocol.actorsZ-github.com/eigr/go-support/eigr/actors;actorsb\x06proto3')



_REGISTRY = DESCRIPTOR.message_types_by_name['Registry']
_REGISTRY_ACTORSENTRY = _REGISTRY.nested_types_by_name['ActorsEntry']
_ACTORSYSTEM = DESCRIPTOR.message_types_by_name['ActorSystem']
_ACTORSNAPSHOTSTRATEGY = DESCRIPTOR.message_types_by_name['ActorSnapshotStrategy']
_ACTORDEACTIVATESTRATEGY = DESCRIPTOR.message_types_by_name['ActorDeactivateStrategy']
_TIMEOUTSTRATEGY = DESCRIPTOR.message_types_by_name['TimeoutStrategy']
_ACTORSTATE = DESCRIPTOR.message_types_by_name['ActorState']
_ACTORSTATE_TAGSENTRY = _ACTORSTATE.nested_types_by_name['TagsEntry']
_ACTOR = DESCRIPTOR.message_types_by_name['Actor']
Registry = _reflection.GeneratedProtocolMessageType('Registry', (_message.Message,), {

  'ActorsEntry' : _reflection.GeneratedProtocolMessageType('ActorsEntry', (_message.Message,), {
    'DESCRIPTOR' : _REGISTRY_ACTORSENTRY,
    '__module__' : 'protobuf.eigr.actor_pb2'
    # @@protoc_insertion_point(class_scope:eigr.actors.Registry.ActorsEntry)
    })
  ,
  'DESCRIPTOR' : _REGISTRY,
  '__module__' : 'protobuf.eigr.actor_pb2'
  # @@protoc_insertion_point(class_scope:eigr.actors.Registry)
  })
_sym_db.RegisterMessage(Registry)
_sym_db.RegisterMessage(Registry.ActorsEntry)

ActorSystem = _reflection.GeneratedProtocolMessageType('ActorSystem', (_message.Message,), {
  'DESCRIPTOR' : _ACTORSYSTEM,
  '__module__' : 'protobuf.eigr.actor_pb2'
  # @@protoc_insertion_point(class_scope:eigr.actors.ActorSystem)
  })
_sym_db.RegisterMessage(ActorSystem)

ActorSnapshotStrategy = _reflection.GeneratedProtocolMessageType('ActorSnapshotStrategy', (_message.Message,), {
  'DESCRIPTOR' : _ACTORSNAPSHOTSTRATEGY,
  '__module__' : 'protobuf.eigr.actor_pb2'
  # @@protoc_insertion_point(class_scope:eigr.actors.ActorSnapshotStrategy)
  })
_sym_db.RegisterMessage(ActorSnapshotStrategy)

ActorDeactivateStrategy = _reflection.GeneratedProtocolMessageType('ActorDeactivateStrategy', (_message.Message,), {
  'DESCRIPTOR' : _ACTORDEACTIVATESTRATEGY,
  '__module__' : 'protobuf.eigr.actor_pb2'
  # @@protoc_insertion_point(class_scope:eigr.actors.ActorDeactivateStrategy)
  })
_sym_db.RegisterMessage(ActorDeactivateStrategy)

TimeoutStrategy = _reflection.GeneratedProtocolMessageType('TimeoutStrategy', (_message.Message,), {
  'DESCRIPTOR' : _TIMEOUTSTRATEGY,
  '__module__' : 'protobuf.eigr.actor_pb2'
  # @@protoc_insertion_point(class_scope:eigr.actors.TimeoutStrategy)
  })
_sym_db.RegisterMessage(TimeoutStrategy)

ActorState = _reflection.GeneratedProtocolMessageType('ActorState', (_message.Message,), {

  'TagsEntry' : _reflection.GeneratedProtocolMessageType('TagsEntry', (_message.Message,), {
    'DESCRIPTOR' : _ACTORSTATE_TAGSENTRY,
    '__module__' : 'protobuf.eigr.actor_pb2'
    # @@protoc_insertion_point(class_scope:eigr.actors.ActorState.TagsEntry)
    })
  ,
  'DESCRIPTOR' : _ACTORSTATE,
  '__module__' : 'protobuf.eigr.actor_pb2'
  # @@protoc_insertion_point(class_scope:eigr.actors.ActorState)
  })
_sym_db.RegisterMessage(ActorState)
_sym_db.RegisterMessage(ActorState.TagsEntry)

Actor = _reflection.GeneratedProtocolMessageType('Actor', (_message.Message,), {
  'DESCRIPTOR' : _ACTOR,
  '__module__' : 'protobuf.eigr.actor_pb2'
  # @@protoc_insertion_point(class_scope:eigr.actors.Actor)
  })
_sym_db.RegisterMessage(Actor)

if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'\n!io.eigr.functions.protocol.actorsZ-github.com/eigr/go-support/eigr/actors;actors'
  _REGISTRY_ACTORSENTRY._options = None
  _REGISTRY_ACTORSENTRY._serialized_options = b'8\001'
  _ACTORSTATE_TAGSENTRY._options = None
  _ACTORSTATE_TAGSENTRY._serialized_options = b'8\001'
  _REGISTRY._serialized_start=70
  _REGISTRY._serialized_end=198
  _REGISTRY_ACTORSENTRY._serialized_start=133
  _REGISTRY_ACTORSENTRY._serialized_end=198
  _ACTORSYSTEM._serialized_start=200
  _ACTORSYSTEM._serialized_end=268
  _ACTORSNAPSHOTSTRATEGY._serialized_start=270
  _ACTORSNAPSHOTSTRATEGY._serialized_end=354
  _ACTORDEACTIVATESTRATEGY._serialized_start=356
  _ACTORDEACTIVATESTRATEGY._serialized_end=442
  _TIMEOUTSTRATEGY._serialized_start=444
  _TIMEOUTSTRATEGY._serialized_end=478
  _ACTORSTATE._serialized_start=481
  _ACTORSTATE._serialized_end=624
  _ACTORSTATE_TAGSENTRY._serialized_start=581
  _ACTORSTATE_TAGSENTRY._serialized_end=624
  _ACTOR._serialized_start=627
  _ACTOR._serialized_end=838
# @@protoc_insertion_point(module_scope)
